### PR TITLE
Updated styling for website, added sidebar

### PR DESCRIPTION
**Pull request by jlin00**

### CODE REVIEW

**Review by phuang00 — CHANGES_REQUESTED** [review]
Looks good overall. Just a few quick questions:
- for Remind me entry in form, shouldn't we let users know that it's in days?
- for expiration date, do we want to allow them to enter dates that have already passed?
- (more of a future thing) alerts kind of shifts the page when it disappears which makes it a bit annoying, should we fix that?

The errors that are caught in the frontend are fine, didn't find anything wrong with them. Not actual routes so didn't check anything that would need to be caught in backend.

**Comment by phuang00** [comment]
Oh i also separated out the dummy page into dummy form and page.

**Comment by jlin00** [comment]
> Looks good overall. Just a few quick questions:
> 
> * for Remind me entry in form, shouldn't we let users know that it's in days?
> * for expiration date, do we want to allow them to enter dates that have already passed?
> * (more of a future thing) alerts kind of shifts the page when it disappears which makes it a bit annoying, should we fix that?
> 
> The errors that are caught in the frontend are fine, didn't find anything wrong with them. Not actual routes so didn't check anything that would need to be caught in backend.

- Yes, we can just add that later. This was just an example.
- Users can keep groceries in their pantry after expiration, so we should also allow them to add expiration dates that already passed. 
- Sure, we can fix it; it's kind of annoying though.

**Comment by phuang00** [comment]
Gotcha, we can merge it first and then address the changes in beta

**Review by phuang00 — APPROVED** [review]
Merge in first, address minor issues later

**Pull request merged**
